/*
 * generated by Xtext 2.11.0
 */
package com.dslconsultancy.uiscript.xtext.ide


/**
 * Use this class to register ide components.
 */
class UIScriptIdeModule extends AbstractUIScriptIdeModule {
}
