/*
 * generated by Xtext 2.11.0
 */
package com.dslconsultancy.uiscript.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UIScriptRuntimeModule extends AbstractUIScriptRuntimeModule {
}
